/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 */
public class VistaActividad extends javax.swing.JPanel
{
    /**
     * Constructor de la clase 'VistaActividad'
     */
    public VistaActividad()
    {
        setSize(getWidth(), getHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jScrollPane_actividades = new javax.swing.JScrollPane();
        jTable_actividades = new javax.swing.JTable();
        jButton_nuevaActividad = new javax.swing.JButton();
        jButton_borrarActividad = new javax.swing.JButton();
        jButton_actualizarActividad = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1536, 864));

        jLabel_titulo.setFont(new java.awt.Font("Noto Sans Lao", 1, 36)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Gestión de Actividades");
        jLabel_titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_titulo.setMaximumSize(new java.awt.Dimension(408, 100));
        jLabel_titulo.setMinimumSize(new java.awt.Dimension(408, 100));
        jLabel_titulo.setPreferredSize(new java.awt.Dimension(408, 100));

        jTable_actividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_actividades.setViewportView(jTable_actividades);

        jButton_nuevaActividad.setText("Nueva Actividad");
        jButton_nuevaActividad.setActionCommand("NuevaActividad");
        jButton_nuevaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevaActividadActionPerformed(evt);
            }
        });

        jButton_borrarActividad.setText("Borrar Actividad");
        jButton_borrarActividad.setActionCommand("BorrarActividad");
        jButton_borrarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrarActividadActionPerformed(evt);
            }
        });

        jButton_actualizarActividad.setText("Actualizar Actividad");
        jButton_actualizarActividad.setActionCommand("ActualizarActividad");
        jButton_actualizarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_actividades)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_nuevaActividad)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_borrarActividad)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_actualizarActividad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_actividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_nuevaActividad)
                    .addComponent(jButton_borrarActividad)
                    .addComponent(jButton_actualizarActividad))
                .addContainerGap(290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Boton para insertar una Actividad 'Nueva Actividad'
     * @param evt 
     */
    private void jButton_nuevaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevaActividadActionPerformed
        
    }//GEN-LAST:event_jButton_nuevaActividadActionPerformed

    /**
     * Boton para eliminar una Actividad 'Borrar Actividad'
     * @param evt 
     */
    private void jButton_borrarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrarActividadActionPerformed
        
    }//GEN-LAST:event_jButton_borrarActividadActionPerformed

    /**
     * Boton para actualizar una Actividad 'Actualizar Actividad'
     * @param evt 
     */
    private void jButton_actualizarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActividadActionPerformed
        
    }//GEN-LAST:event_jButton_actualizarActividadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_actualizarActividad;
    public javax.swing.JButton jButton_borrarActividad;
    public javax.swing.JButton jButton_nuevaActividad;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane_actividades;
    public javax.swing.JTable jTable_actividades;
    // End of variables declaration//GEN-END:variables
}
