/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 * 'JDialog' para insertar (Nuevo Monitor) o modificar (Acualizar Monitor) un Monitor en la BD
 */
public class VistaMonitorCRUD extends javax.swing.JDialog
{
    /**
     * Constructor de la clase 'VistaMonitorCRUD'
     */
    public VistaMonitorCRUD()
    {
        setSize(700, 300); // Tamaño de la ventana
        setLayout(null); // Diseño absoluto
        initComponents();
        this.jTextField_nombre.requestFocusInWindow(); // Posicionamos el cursor en el campo 'nombre'
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_fechaNac = new javax.swing.JLabel();
        jDateChooser_fechaEntrada = new com.toedter.calendar.JDateChooser();
        jTextField_codigo = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jButton_aceptarM = new javax.swing.JButton();
        jTextField_dni = new javax.swing.JTextField();
        jButton_cancelarM = new javax.swing.JButton();
        jLabel_correo = new javax.swing.JLabel();
        jLabel_fechaEntrada = new javax.swing.JLabel();
        jLabel_codigo = new javax.swing.JLabel();
        jLabel_categoria = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_dni = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        jTextField_nick = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_fechaNac.setText("Teléfono");

        jTextField_codigo.setEditable(false);
        jTextField_codigo.setBackground(new java.awt.Color(226, 229, 233));
        jTextField_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoActionPerformed(evt);
            }
        });

        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jButton_aceptarM.setText("Aceptar");
        jButton_aceptarM.setActionCommand("AceptarMonitor");
        jButton_aceptarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarMActionPerformed(evt);
            }
        });

        jTextField_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dniActionPerformed(evt);
            }
        });

        jButton_cancelarM.setText("Cancelar");
        jButton_cancelarM.setActionCommand("CancelarMonitor");
        jButton_cancelarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarMActionPerformed(evt);
            }
        });

        jLabel_correo.setText("Correo");

        jLabel_fechaEntrada.setText("* Fecha de Entrada");

        jLabel_codigo.setText("* Código");

        jLabel_categoria.setText("Nick");

        jLabel_nombre.setText("* Nombre");

        jLabel_dni.setText("* DNI");

        jTextField_nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nombre)
                    .addComponent(jLabel_dni)
                    .addComponent(jLabel_codigo)
                    .addComponent(jLabel_fechaNac))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_fechaEntrada)
                    .addComponent(jLabel_categoria)
                    .addComponent(jLabel_correo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser_fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jButton_aceptarM)
                .addGap(18, 18, 18)
                .addComponent(jButton_cancelarM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_codigo)
                            .addComponent(jLabel_correo))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_nombre))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_fechaEntrada)
                            .addGap(7, 7, 7))
                        .addComponent(jDateChooser_fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dni)
                    .addComponent(jLabel_categoria)
                    .addComponent(jTextField_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fechaNac)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aceptarM)
                    .addComponent(jButton_cancelarM))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Campo de texto NO editable del 'codMonitor' del Monitor
     * @param evt 
     */
    private void jTextField_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoActionPerformed
        this.jTextField_codigo.setEditable(false); // Hacemos que el campo 'Codigo' NO sea editable, es decir, que NO se pueda escribir
    }//GEN-LAST:event_jTextField_codigoActionPerformed

    /**
     * Campo de texto del 'nombre' del Monitor
     * @param evt 
     */
    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
    
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    /**
     * Boton 'Aceptar' para Insertar/Actualizar un Monitor
     * @param evt 
     */
    private void jButton_aceptarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarMActionPerformed

    }//GEN-LAST:event_jButton_aceptarMActionPerformed

    /**
     * Campo de texto del 'dni' del Monitor
     * @param evt 
     */
    private void jTextField_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dniActionPerformed

    }//GEN-LAST:event_jTextField_dniActionPerformed

    /**
     * Campo de texto del 'nick' del Monitor
     * @param evt 
     */
    private void jTextField_nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nickActionPerformed
        
    }//GEN-LAST:event_jTextField_nickActionPerformed

    /**
     * Boton 'Cancelar' para Insertar/Actualizar un Monitor
     * @param evt 
     */
    private void jButton_cancelarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarMActionPerformed
        
    }//GEN-LAST:event_jButton_cancelarMActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_aceptarM;
    public javax.swing.JButton jButton_cancelarM;
    public com.toedter.calendar.JDateChooser jDateChooser_fechaEntrada;
    private javax.swing.JLabel jLabel_categoria;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_dni;
    private javax.swing.JLabel jLabel_fechaEntrada;
    private javax.swing.JLabel jLabel_fechaNac;
    private javax.swing.JLabel jLabel_nombre;
    public javax.swing.JTextField jTextField_codigo;
    public javax.swing.JTextField jTextField_correo;
    public javax.swing.JTextField jTextField_dni;
    public javax.swing.JTextField jTextField_nick;
    public javax.swing.JTextField jTextField_nombre;
    public javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
};
