
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 * 'JPanel' para la Vista de la Pantalla de Inicio (se muestra por defecto tras realizar la conexion con exito)
 */
public class VistaIncio extends javax.swing.JPanel
{
    /**
     * Constructor de la clase 'VistaInicio'
     */
    public VistaIncio()
    {
        setSize(getWidth(), getHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel_img = new javax.swing.JLabel();
        jLabel_asignatura = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_gradoUniversitario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(218, 254, 1));

        jLabel_titulo.setFont(new java.awt.Font("Noto Sans Lao", 1, 36)); // NOI18N
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Bienvenido al SGBD del Gimnasio");

        jLabel_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/GYM_grande.png"))); // NOI18N

        jLabel_asignatura.setFont(new java.awt.Font("Noto Sans Lao", 1, 18)); // NOI18N
        jLabel_asignatura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_asignatura.setText("Diseño y Desarrollo de Sistemas de Información (DDSI)");

        jLabel_nombre.setFont(new java.awt.Font("Noto Sans Lao", 1, 18)); // NOI18N
        jLabel_nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_nombre.setText("Antonio Abad Hernández Gálvez");

        jLabel_gradoUniversitario.setFont(new java.awt.Font("Noto Sans Lao", 1, 18)); // NOI18N
        jLabel_gradoUniversitario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_gradoUniversitario.setText("Grado en Ingeniería Informática");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_asignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_gradoUniversitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_titulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel_img)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jLabel_gradoUniversitario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_asignatura)
                .addGap(18, 18, 18)
                .addComponent(jLabel_nombre)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_asignatura;
    private javax.swing.JLabel jLabel_gradoUniversitario;
    private javax.swing.JLabel jLabel_img;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_titulo;
    // End of variables declaration//GEN-END:variables
};
