/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 */
public class VistaMonitor extends javax.swing.JPanel
{
    /**
     * Constructor de la clase 'VistaMonitor'
     */
    public VistaMonitor()
    {
        setSize(getWidth(), getHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jScrollPane_monitores = new javax.swing.JScrollPane();
        jTable_monitores = new javax.swing.JTable();
        jButton_nuevoMonitor = new javax.swing.JButton();
        jButton_borrarMonitor = new javax.swing.JButton();
        jButton_actualizarMonitor = new javax.swing.JButton();

        jLabel_titulo.setFont(new java.awt.Font("Noto Sans Lao", 1, 36)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Gestión de Monitores");
        jLabel_titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_titulo.setMaximumSize(new java.awt.Dimension(383, 100));
        jLabel_titulo.setMinimumSize(new java.awt.Dimension(383, 100));
        jLabel_titulo.setPreferredSize(new java.awt.Dimension(383, 100));
        jLabel_titulo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jTable_monitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_monitores.setViewportView(jTable_monitores);

        jButton_nuevoMonitor.setText("Nuevo Monitor");
        jButton_nuevoMonitor.setActionCommand("NuevoMonitor");
        jButton_nuevoMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevoMonitorActionPerformed(evt);
            }
        });

        jButton_borrarMonitor.setText("Borrar Monitor");
        jButton_borrarMonitor.setActionCommand("BorrarMonitor");
        jButton_borrarMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrarMonitorActionPerformed(evt);
            }
        });

        jButton_actualizarMonitor.setText("Actualizar Monitor");
        jButton_actualizarMonitor.setActionCommand("ActualizarMonitor");
        jButton_actualizarMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarMonitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_monitores)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_nuevoMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_borrarMonitor)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_actualizarMonitor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_monitores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_nuevoMonitor)
                    .addComponent(jButton_borrarMonitor)
                    .addComponent(jButton_actualizarMonitor))
                .addContainerGap(272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton para actualizar un Monitor 'Actualizar Monitor'
     * @param evt 
     */
    private void jButton_actualizarMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarMonitorActionPerformed
        
    }//GEN-LAST:event_jButton_actualizarMonitorActionPerformed

    /**
     * Boton para insertar un Monitor 'Nuevo Monitor'
     * @param evt 
     */
    private void jButton_nuevoMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevoMonitorActionPerformed
        
    }//GEN-LAST:event_jButton_nuevoMonitorActionPerformed

    /**
     * Boton para eliminar un Monitor 'Borrar Monitor'
     * @param evt 
     */
    private void jButton_borrarMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrarMonitorActionPerformed
        
    }//GEN-LAST:event_jButton_borrarMonitorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_actualizarMonitor;
    public javax.swing.JButton jButton_borrarMonitor;
    public javax.swing.JButton jButton_nuevoMonitor;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane_monitores;
    public javax.swing.JTable jTable_monitores;
    // End of variables declaration//GEN-END:variables
}
