/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 * 'JDialog' para inscribir (Dar de Alta) o borrar (Dar de Baja) a un Socio en una Actividad en la BD
 */
public class VistaInscripcionCRUD extends javax.swing.JDialog
{
    /**
     * Constructor de la clase 'VistaInscripcionCRUD'
     */
    public VistaInscripcionCRUD()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_textActividad = new javax.swing.JLabel();
        jComboBox_actividad = new javax.swing.JComboBox<>();
        jButton_aceptarI = new javax.swing.JButton();
        jButton_cancelarI = new javax.swing.JButton();
        jLabel_txtSocio = new javax.swing.JLabel();
        jTextField_nombreSocio = new javax.swing.JTextField();
        jLabel_txtCodigo = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_textActividad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_textActividad.setText("Selecciona la Actividad:");

        jButton_aceptarI.setText("Aceptar");
        jButton_aceptarI.setActionCommand("AceptarI");

        jButton_cancelarI.setText("Cancelar");
        jButton_cancelarI.setActionCommand("CancelarI");

        jLabel_txtSocio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_txtSocio.setText("Nombre:");

        jTextField_nombreSocio.setEditable(false);
        jTextField_nombreSocio.setBackground(new java.awt.Color(226, 229, 233));
        jTextField_nombreSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreSocioActionPerformed(evt);
            }
        });

        jLabel_txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_txtCodigo.setText("Código:");

        jTextField_codigo.setEditable(false);
        jTextField_codigo.setBackground(new java.awt.Color(226, 229, 233));
        jTextField_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButton_aceptarI)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_cancelarI))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_textActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_txtSocio)
                                    .addComponent(jLabel_txtCodigo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_nombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_txtCodigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_nombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_txtSocio))
                .addGap(36, 36, 36)
                .addComponent(jLabel_textActividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cancelarI)
                    .addComponent(jButton_aceptarI))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Campo de texto NO editable del 'nombre' del Socio que queremos insertar en la Actividad
     * @param evt 
     */
    private void jTextField_nombreSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreSocioActionPerformed
        this.jTextField_nombreSocio.setEditable(false); // Hacemos que el campo 'Nombre' NO sea editable, es decir, que NO se pueda escribir
    }//GEN-LAST:event_jTextField_nombreSocioActionPerformed

    /**
     * Campo de texto NO editable del 'numeroSocio' del Socio que queremos insertar en la Actividad
     * @param evt 
     */
    private void jTextField_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoActionPerformed
        this.jTextField_codigo.setEditable(false); // Hacemos que el campo 'Codigo' NO sea editable, es decir, que NO se pueda escribir
    }//GEN-LAST:event_jTextField_codigoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_aceptarI;
    public javax.swing.JButton jButton_cancelarI;
    public javax.swing.JComboBox<String> jComboBox_actividad;
    private javax.swing.JLabel jLabel_textActividad;
    private javax.swing.JLabel jLabel_txtCodigo;
    private javax.swing.JLabel jLabel_txtSocio;
    public javax.swing.JTextField jTextField_codigo;
    public javax.swing.JTextField jTextField_nombreSocio;
    // End of variables declaration//GEN-END:variables
};
