/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorConexion;
import java.awt.event.KeyEvent;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 * 'JFrame' para la Vista de la Pantalla de Conexion
 */
public class VistaConexion extends javax.swing.JFrame
{
    /**
     * Constructor de la clase 'VistaConexion'
     */
    public VistaConexion()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_conexion = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jLabel_txtUsuario = new javax.swing.JLabel();
        jLabel_txtPassword = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jTextField_password = new javax.swing.JPasswordField();
        jButton_entrar = new javax.swing.JButton();
        jButton_cancelar = new javax.swing.JButton();
        jLabel_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Antonio Abad Hernández Gálvez -> Inicio de Sesión");
        setBackground(new java.awt.Color(242, 242, 242));
        setResizable(false);
        setSize(new java.awt.Dimension(1536, 864));

        jLabel_titulo.setFont(new java.awt.Font("Noto Sans Lao", 1, 18)); // NOI18N
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("SGBD del Gimnasio 'GYMTONY'");

        jLabel_txtUsuario.setFont(new java.awt.Font("Noto Sans Lao", 0, 18)); // NOI18N
        jLabel_txtUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_txtUsuario.setText("Usuario");

        jLabel_txtPassword.setFont(new java.awt.Font("Noto Sans Lao", 0, 18)); // NOI18N
        jLabel_txtPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_txtPassword.setText("Contraseña");

        jTextField_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usuarioActionPerformed(evt);
            }
        });
        jTextField_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usuarioKeyPressed(evt);
            }
        });

        jTextField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_passwordActionPerformed(evt);
            }
        });
        jTextField_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_passwordKeyPressed(evt);
            }
        });

        jButton_entrar.setText("Entrar");
        jButton_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_entrarActionPerformed(evt);
            }
        });

        jButton_cancelar.setText("Cancelar");
        jButton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarActionPerformed(evt);
            }
        });

        jLabel_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/GYM_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_conexionLayout = new javax.swing.GroupLayout(jPanel_conexion);
        jPanel_conexion.setLayout(jPanel_conexionLayout);
        jPanel_conexionLayout.setHorizontalGroup(
            jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_conexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_img, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_conexionLayout.createSequentialGroup()
                                .addComponent(jLabel_txtPassword)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_conexionLayout.createSequentialGroup()
                                .addComponent(jLabel_txtUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jTextField_password))
                        .addGap(512, 512, 512))
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jButton_entrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_cancelar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel_conexionLayout.createSequentialGroup()
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_conexionLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_password, jTextField_usuario});

        jPanel_conexionLayout.setVerticalGroup(
            jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_conexionLayout.createSequentialGroup()
                .addComponent(jLabel_titulo)
                .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_usuario)
                            .addComponent(jLabel_txtUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_txtPassword))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_entrar)
                            .addComponent(jButton_cancelar))
                        .addGap(543, 543, 543))
                    .addGroup(jPanel_conexionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_img)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_conexion, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton 'Cancelar' del Establecimiento de la Conexion
     * @param evt 
     */
    private void jButton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarActionPerformed
        
    }//GEN-LAST:event_jButton_cancelarActionPerformed

    /**
     * Boton 'Entrar' del Establecimiento de la Conexion
     * Establece el usuario y la contraseña introducida por teclado en los atributos privados de la clase 'ControladorConexion'
     * @param evt 
     */
    private void jButton_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_entrarActionPerformed
        ControladorConexion.user=this.jTextField_usuario.getText();
        ControladorConexion.pass=new String(this.jTextField_password.getPassword());
    }//GEN-LAST:event_jButton_entrarActionPerformed

    /**
     * Campo de texto del 'usuario' con el que queremos Iniciar Sesion
     * @param evt 
     */
    private void jTextField_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usuarioActionPerformed
        
    }//GEN-LAST:event_jTextField_usuarioActionPerformed

    /**
     * Si estamos encima del campo 'txtUsuario' y presionamos la tecla 'ENTER', es como si hicieramos clic en el boton 'jButton_entrar' 
     * @param evt 
     */
    private void jTextField_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usuarioKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ESCAPE) // Si estamos encima del campo 'txtUsuario' y presionamos la tecla 'ESC', es como si hicieramos clic en el boton 'jButton_cancelar'
        {
            this.jButton_cancelar.requestFocus();
            this.jButton_cancelar.doClick();
        }
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER)
        {
            this.jButton_entrar.requestFocus();
            this.jButton_entrar.doClick();
        }
    }//GEN-LAST:event_jTextField_usuarioKeyPressed

    /**
     * Si estamos encima del campo 'txtPassword' y presionamos la tecla 'ENTER', es como si hicieramos clic en el boton 'jButton_entrar'
     * @param evt 
     */
    private void jTextField_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_passwordKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ESCAPE) // Si estamos encima del campo 'txtUsuario' y presionamos la tecla 'ESC', es como si hicieramos clic en el boton 'jButton_cancelar'
        {
            this.jButton_cancelar.requestFocus();
            this.jButton_cancelar.doClick();
        }
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER)
        {
            jButton_entrar.requestFocus();
            jButton_entrar.doClick();
        }
    }//GEN-LAST:event_jTextField_passwordKeyPressed

    /**
     * Campo de texto de la 'contraseña' con la que queremos Iniciar Sesion
     * @param evt 
     */
    private void jTextField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_passwordActionPerformed
        
    }//GEN-LAST:event_jTextField_passwordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_cancelar;
    public javax.swing.JButton jButton_entrar;
    private javax.swing.JLabel jLabel_img;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_txtPassword;
    private javax.swing.JLabel jLabel_txtUsuario;
    private javax.swing.JPanel jPanel_conexion;
    public javax.swing.JPasswordField jTextField_password;
    public javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
};
