/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 * 'JDialog' para insertar (Nuevo Socio) o modificar (Acualizar Socio) un Socio en la BD
 */
public class VistaSocioCRUD extends javax.swing.JDialog
{
    /**
     * Constructor de la clase 'VistaSocioCRUD'
     */
    public VistaSocioCRUD()
    {
        setSize(700, 300); // Tamaño de la ventana
        setLayout(null); // Diseño absoluto
        initComponents();
        this.jTextField_nombre.requestFocusInWindow(); // Posicionamos el cursor en el campo 'nombre'
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_fechaNac = new javax.swing.JLabel();
        jDateChooser_fechaEntrada = new com.toedter.calendar.JDateChooser();
        jTextField_codigo = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jButton_aceptarS = new javax.swing.JButton();
        jTextField_dni = new javax.swing.JTextField();
        jButton_cancelarS = new javax.swing.JButton();
        jDateChooser_fechaNac = new com.toedter.calendar.JDateChooser();
        jLabel_telefono = new javax.swing.JLabel();
        jLabel_correo = new javax.swing.JLabel();
        jLabel_fechaEntrada = new javax.swing.JLabel();
        jLabel_codigo = new javax.swing.JLabel();
        jLabel_categoria = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jLabel_dni = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        jComboBox_categoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_fechaNac.setText("Fecha de Nacimiento");

        jTextField_codigo.setEditable(false);
        jTextField_codigo.setBackground(new java.awt.Color(226, 229, 233));
        jTextField_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoActionPerformed(evt);
            }
        });

        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jButton_aceptarS.setText("Aceptar");
        jButton_aceptarS.setActionCommand("AceptarSocio");
        jButton_aceptarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarSActionPerformed(evt);
            }
        });

        jTextField_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dniActionPerformed(evt);
            }
        });

        jButton_cancelarS.setText("Cancelar");
        jButton_cancelarS.setActionCommand("CancelarSocio");
        jButton_cancelarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarSActionPerformed(evt);
            }
        });

        jLabel_telefono.setText("Teléfono");

        jLabel_correo.setText("Correo");

        jLabel_fechaEntrada.setText("* Fecha de Entrada");

        jLabel_codigo.setText("* Código");

        jLabel_categoria.setText("* Categoría");

        jLabel_nombre.setText("* Nombre");

        jTextField_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telefonoActionPerformed(evt);
            }
        });

        jLabel_dni.setText("* DNI");

        jTextField_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correoActionPerformed(evt);
            }
        });

        jComboBox_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        jComboBox_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_aceptarS)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_codigo)
                                    .addComponent(jLabel_nombre)
                                    .addComponent(jLabel_dni))
                                .addGap(78, 78, 78))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_fechaNac)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_categoria)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_fechaEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_telefono)
                                .addComponent(jLabel_correo)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_cancelarS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_telefono))
                                .addGap(21, 21, 21)
                                .addComponent(jTextField_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_fechaEntrada)
                                .addGap(7, 7, 7))
                            .addComponent(jDateChooser_fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_categoria)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_codigo))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombre)
                            .addComponent(jLabel_correo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_dni)
                            .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_fechaNac))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aceptarS)
                    .addComponent(jButton_cancelarS))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Campo de texto NO editable del 'numeroSocio' del Socio
     * @param evt 
     */
    private void jTextField_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoActionPerformed
        this.jTextField_codigo.setEditable(false); // Hacemos que el campo 'Codigo' NO sea editable, es decir, que NO se pueda escribir
    }//GEN-LAST:event_jTextField_codigoActionPerformed

    /**
     * Campo de texto del 'nombre' del Socio
     * @param evt 
     */
    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    /**
     * Boton 'Aceptar' para Insertar/Actualizar el Socio
     * @param evt 
     */
    private void jButton_aceptarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarSActionPerformed
        
    }//GEN-LAST:event_jButton_aceptarSActionPerformed

    /**
     * Campo de texto del 'dni' del Socio
     * @param evt 
     */
    private void jTextField_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dniActionPerformed
        
    }//GEN-LAST:event_jTextField_dniActionPerformed

    /**
     * Campo de texto del 'telefono' del Socio
     * @param evt 
     */
    private void jTextField_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telefonoActionPerformed
        
    }//GEN-LAST:event_jTextField_telefonoActionPerformed

    /**
     * Menu desplegable de la 'categoria' del Socio
     * @param evt 
     */
    private void jComboBox_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaActionPerformed
        
    }//GEN-LAST:event_jComboBox_categoriaActionPerformed

    /**
     * Campo de texto del 'correo' del Socio
     * @param evt 
     */
    private void jTextField_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correoActionPerformed
        
    }//GEN-LAST:event_jTextField_correoActionPerformed

    /**
     * Boton 'Cancelar' para Insertar/Actualizar un Socio
     * @param evt 
     */
    private void jButton_cancelarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarSActionPerformed
        
    }//GEN-LAST:event_jButton_cancelarSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_aceptarS;
    public javax.swing.JButton jButton_cancelarS;
    public javax.swing.JComboBox<String> jComboBox_categoria;
    public com.toedter.calendar.JDateChooser jDateChooser_fechaEntrada;
    public com.toedter.calendar.JDateChooser jDateChooser_fechaNac;
    private javax.swing.JLabel jLabel_categoria;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_dni;
    private javax.swing.JLabel jLabel_fechaEntrada;
    private javax.swing.JLabel jLabel_fechaNac;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_telefono;
    public javax.swing.JTextField jTextField_codigo;
    public javax.swing.JTextField jTextField_correo;
    public javax.swing.JTextField jTextField_dni;
    public javax.swing.JTextField jTextField_nombre;
    public javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
};
