/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 * 'JDialog' para insertar (Nueva Actividad) o modificar (Acualizar Actividad) una Actividad en la BD
 */
public class VistaActividadCRUD extends javax.swing.JDialog
{
    /**
     * Constructor de la clase 'VistaActividadCRUD'
     */
    public VistaActividadCRUD()
    {
        setLayout(null); // Diseño absoluto
        initComponents();
        this.jTextField_nombre.requestFocusInWindow(); // Posicionamos el cursor en el campo 'nombre'
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_hora = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jButton_aceptarA = new javax.swing.JButton();
        jButton_cancelarA = new javax.swing.JButton();
        jLabel_precio = new javax.swing.JLabel();
        jLabel_descripcion = new javax.swing.JLabel();
        jLabel_monitorResponsable = new javax.swing.JLabel();
        jLabel_codigo = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_precio = new javax.swing.JTextField();
        jLabel_dia = new javax.swing.JLabel();
        jComboBox_dia = new javax.swing.JComboBox<>();
        jComboBox_hora = new javax.swing.JComboBox<>();
        jComboBox_monitorResponsable = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_descripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_hora.setText("* Hora");

        jTextField_codigo.setEditable(false);
        jTextField_codigo.setBackground(new java.awt.Color(226, 229, 233));
        jTextField_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoActionPerformed(evt);
            }
        });

        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jButton_aceptarA.setText("Aceptar");
        jButton_aceptarA.setActionCommand("AceptarActividad");
        jButton_aceptarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarAActionPerformed(evt);
            }
        });

        jButton_cancelarA.setText("Cancelar");
        jButton_cancelarA.setActionCommand("CancelarActividad");
        jButton_cancelarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarAActionPerformed(evt);
            }
        });

        jLabel_precio.setText("* Precio Base Mes");

        jLabel_descripcion.setText("Descripción");

        jLabel_monitorResponsable.setText("Monitor Responsable");

        jLabel_codigo.setText("* Código");

        jLabel_nombre.setText("* Nombre");

        jTextField_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_precioActionPerformed(evt);
            }
        });

        jLabel_dia.setText("* Día");

        jComboBox_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        jComboBox_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_diaActionPerformed(evt);
            }
        });

        jComboBox_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_horaActionPerformed(evt);
            }
        });

        jComboBox_monitorResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_monitorResponsableActionPerformed(evt);
            }
        });

        jTextArea_descripcion.setColumns(20);
        jTextArea_descripcion.setLineWrap(true);
        jTextArea_descripcion.setRows(5);
        jTextArea_descripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea_descripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_codigo)
                                            .addComponent(jLabel_nombre)
                                            .addComponent(jLabel_dia))
                                        .addGap(60, 60, 60))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel_hora)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_precio)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_descripcion)
                            .addComponent(jLabel_monitorResponsable)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jComboBox_monitorResponsable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jButton_aceptarA)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_cancelarA)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_codigo)
                    .addComponent(jLabel_descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_dia)
                            .addComponent(jComboBox_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_monitorResponsable)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox_monitorResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_aceptarA)
                            .addComponent(jButton_cancelarA))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_hora))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_precio))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Campo de texto NO editable del 'idActividad' de la Actividad
     * @param evt 
     */
    private void jTextField_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoActionPerformed
        this.jTextField_codigo.setEditable(false); // Hacemos que el campo 'Codigo' NO sea editable, es decir, que NO se pueda escribir
    }//GEN-LAST:event_jTextField_codigoActionPerformed

    /**
     * Campo de texto del 'nombre' de la Actividad
     * @param evt 
     */
    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    /**
     * Boton 'Aceptar' para Insertar/Actualizar una Actividad
     * @param evt 
     */
    private void jButton_aceptarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarAActionPerformed
        
    }//GEN-LAST:event_jButton_aceptarAActionPerformed

    /**
     * Campo de texto del 'precio' de la Actividad
     * @param evt 
     */
    private void jTextField_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_precioActionPerformed
        
    }//GEN-LAST:event_jTextField_precioActionPerformed

    /**
     * Boton 'Cancelar' para Insertar/Actualizar una Actividad
     * @param evt 
     */
    private void jButton_cancelarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarAActionPerformed
        
    }//GEN-LAST:event_jButton_cancelarAActionPerformed

    /**
     * Menu desplegable del 'dia' de la Actividad
     * @param evt 
     */
    private void jComboBox_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_diaActionPerformed
        
    }//GEN-LAST:event_jComboBox_diaActionPerformed

    /**
     * Menu desplegable de la 'hora' de la Actividad
     * @param evt 
     */
    private void jComboBox_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_horaActionPerformed
        
    }//GEN-LAST:event_jComboBox_horaActionPerformed

    /**
     * Menu desplegable del 'monitorResposable' de la Actividad
     * @param evt 
     */
    private void jComboBox_monitorResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_monitorResponsableActionPerformed
        
    }//GEN-LAST:event_jComboBox_monitorResponsableActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_aceptarA;
    public javax.swing.JButton jButton_cancelarA;
    public javax.swing.JComboBox<String> jComboBox_dia;
    public javax.swing.JComboBox<String> jComboBox_hora;
    public javax.swing.JComboBox<String> jComboBox_monitorResponsable;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JLabel jLabel_descripcion;
    private javax.swing.JLabel jLabel_dia;
    private javax.swing.JLabel jLabel_hora;
    private javax.swing.JLabel jLabel_monitorResponsable;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_precio;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea_descripcion;
    public javax.swing.JTextField jTextField_codigo;
    public javax.swing.JTextField jTextField_nombre;
    public javax.swing.JTextField jTextField_precio;
    // End of variables declaration//GEN-END:variables
};
