/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 */
public class VistaSocio extends javax.swing.JPanel
{
    /**
     * Constructor de la clase 'VistaSocio'
     */
    public VistaSocio()
    {
        setSize(getWidth(), getHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jScrollPane_socios = new javax.swing.JScrollPane();
        jTable_socios = new javax.swing.JTable();
        jButton_nuevoSocio = new javax.swing.JButton();
        jButton_actualizarSocio = new javax.swing.JButton();
        jButton_borrarSocio = new javax.swing.JButton();
        jLabel_imgLupa = new javax.swing.JLabel();
        jTextField_buscarSocio = new javax.swing.JTextField();

        jLabel_titulo.setFont(new java.awt.Font("Noto Sans Lao", 1, 36)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Gestión de Socios");

        jTable_socios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_socios.setViewportView(jTable_socios);

        jButton_nuevoSocio.setText("Nuevo Socio");
        jButton_nuevoSocio.setActionCommand("NuevoSocio");
        jButton_nuevoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevoSocioActionPerformed(evt);
            }
        });

        jButton_actualizarSocio.setText("Actualizar Socio");
        jButton_actualizarSocio.setActionCommand("ActualizarSocio");
        jButton_actualizarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarSocioActionPerformed(evt);
            }
        });

        jButton_borrarSocio.setText("Borrar Socio");
        jButton_borrarSocio.setActionCommand("BorrarSocio");
        jButton_borrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrarSocioActionPerformed(evt);
            }
        });

        jLabel_imgLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/img_lupa.png"))); // NOI18N
        jLabel_imgLupa.setText("Buscar (Imagen Lupa)");

        jTextField_buscarSocio.setToolTipText("Introduce el nombre del Socio que quieres buscar");
        jTextField_buscarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_buscarSocioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_socios)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_nuevoSocio)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_borrarSocio)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_actualizarSocio)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_imgLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_buscarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_imgLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField_buscarSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_socios, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_nuevoSocio)
                    .addComponent(jButton_borrarSocio)
                    .addComponent(jButton_actualizarSocio))
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton para insertar un Socio 'Nuevo Socio'
     * @param evt 
     */
    private void jButton_nuevoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevoSocioActionPerformed
        
    }//GEN-LAST:event_jButton_nuevoSocioActionPerformed

    /**
     * Boton para actualizar un Socio 'Actualizar Socio'
     * @param evt 
     */
    private void jButton_actualizarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarSocioActionPerformed
        
    }//GEN-LAST:event_jButton_actualizarSocioActionPerformed

    /**
     * Boton para eliminar un Socio 'Borrar Socio'
     * @param evt 
     */
    private void jButton_borrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrarSocioActionPerformed
        
    }//GEN-LAST:event_jButton_borrarSocioActionPerformed

    /**
     * Campo de texto para buscar un Socio por su campo 'nombre'
     * @param evt 
     */
    private void jTextField_buscarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_buscarSocioActionPerformed
    
    }//GEN-LAST:event_jTextField_buscarSocioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_actualizarSocio;
    public javax.swing.JButton jButton_borrarSocio;
    public javax.swing.JButton jButton_nuevoSocio;
    private javax.swing.JLabel jLabel_imgLupa;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane_socios;
    public javax.swing.JTable jTable_socios;
    public javax.swing.JTextField jTextField_buscarSocio;
    // End of variables declaration//GEN-END:variables
};
