/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 * 'JPanel' de la Vista de la Pantalla Principal sobre la que van el resto de paneles
 */
public class VistaPrincipal extends javax.swing.JFrame
{
    /**
     * Constructor de la clase 'VistaPrincipal'
     */
    public VistaPrincipal()
    {
        setSize(getWidth(), getHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar_inicio = new javax.swing.JMenuBar();
        jMenu_inicio = new javax.swing.JMenu();
        jMenuItem_inicio = new javax.swing.JMenuItem();
        jMenu_monitores = new javax.swing.JMenu();
        jMenuItem_monitores = new javax.swing.JMenuItem();
        jMenu_socios = new javax.swing.JMenu();
        jMenuItem_socios = new javax.swing.JMenuItem();
        jMenuItem_inscripcionSocio = new javax.swing.JMenuItem();
        jMenu_actividades = new javax.swing.JMenu();
        jMenuItem_actividades = new javax.swing.JMenuItem();
        jMenu_salir = new javax.swing.JMenu();
        jMenuItem_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 242, 242));
        setName("frame_principal"); // NOI18N
        setSize(new java.awt.Dimension(1536, 864));

        jMenu_inicio.setText("Inicio");

        jMenuItem_inicio.setText("Volver a la página principal");
        jMenuItem_inicio.setActionCommand("INICIO");
        jMenuItem_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_inicioActionPerformed(evt);
            }
        });
        jMenu_inicio.add(jMenuItem_inicio);

        jMenuBar_inicio.add(jMenu_inicio);

        jMenu_monitores.setText("Monitores");

        jMenuItem_monitores.setText("Gestión de Monitores");
        jMenuItem_monitores.setActionCommand("MONITOR");
        jMenuItem_monitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_monitoresActionPerformed(evt);
            }
        });
        jMenu_monitores.add(jMenuItem_monitores);

        jMenuBar_inicio.add(jMenu_monitores);

        jMenu_socios.setText("Socios");

        jMenuItem_socios.setText("Gestión de Socios");
        jMenuItem_socios.setActionCommand("SOCIO");
        jMenuItem_socios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_sociosActionPerformed(evt);
            }
        });
        jMenu_socios.add(jMenuItem_socios);

        jMenuItem_inscripcionSocio.setText("Gestión de Inscripciones");
        jMenuItem_inscripcionSocio.setActionCommand("GestionInscripcion");
        jMenuItem_inscripcionSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_inscripcionSocioActionPerformed(evt);
            }
        });
        jMenu_socios.add(jMenuItem_inscripcionSocio);

        jMenuBar_inicio.add(jMenu_socios);

        jMenu_actividades.setText("Actividades");

        jMenuItem_actividades.setText("Gestión de Actividades");
        jMenuItem_actividades.setActionCommand("ACTIVIDAD");
        jMenuItem_actividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_actividadesActionPerformed(evt);
            }
        });
        jMenu_actividades.add(jMenuItem_actividades);

        jMenuBar_inicio.add(jMenu_actividades);

        jMenu_salir.setText("Salir");

        jMenuItem_salir.setText("Salir de la Aplicación");
        jMenuItem_salir.setActionCommand("SALIR");
        jMenuItem_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_salirActionPerformed(evt);
            }
        });
        jMenu_salir.add(jMenuItem_salir);

        jMenuBar_inicio.add(jMenu_salir);

        setJMenuBar(jMenuBar_inicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 841, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opcion del 'jMenuBar' para acceder a la 'VistaIncricpion'
     * @param evt 
     */
    private void jMenuItem_inscripcionSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_inscripcionSocioActionPerformed
        
    }//GEN-LAST:event_jMenuItem_inscripcionSocioActionPerformed
    
    /**
     * Opcion del 'jMenuBar' para acceder a la 'VistaInicio'
     * @param evt 
     */
    private void jMenuItem_inicioActionPerformed(java.awt.event.ActionEvent evt)
    {
        
    }
    
    /**
     * Opcion del 'jMenuBar' para acceder a la 'VistaSocio'
     * @param evt 
     */
    private void jMenuItem_sociosActionPerformed(java.awt.event.ActionEvent evt)
    {
        
    }
    
    /**
     * Opcion del 'jMenuBar' para acceder a la 'VistaMonitor'
     * @param evt 
     */
    private void jMenuItem_monitoresActionPerformed(java.awt.event.ActionEvent evt)
    {
        
    }
    
    /**
     * Opcion del 'jMenuBar' para acceder a la 'VistaActividad'
     * @param evt 
     */
    private void jMenuItem_actividadesActionPerformed(java.awt.event.ActionEvent evt)
    {
        
    }
    
    /**
     * Opcion del 'jMenuBar' para salir del Programa
     * @param evt 
     */
    private void jMenuItem_salirActionPerformed(java.awt.event.ActionEvent evt)
    {
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar_inicio;
    public javax.swing.JMenuItem jMenuItem_actividades;
    public javax.swing.JMenuItem jMenuItem_inicio;
    public javax.swing.JMenuItem jMenuItem_inscripcionSocio;
    public javax.swing.JMenuItem jMenuItem_monitores;
    public javax.swing.JMenuItem jMenuItem_salir;
    public javax.swing.JMenuItem jMenuItem_socios;
    private javax.swing.JMenu jMenu_actividades;
    private javax.swing.JMenu jMenu_inicio;
    private javax.swing.JMenu jMenu_monitores;
    private javax.swing.JMenu jMenu_salir;
    private javax.swing.JMenu jMenu_socios;
    // End of variables declaration//GEN-END:variables
}
