/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 * @version 09/02/25
 * @author Antonio Abad Hernandez Galvez
 */
public class VistaInscripcion extends javax.swing.JPanel
{
    /**
     * Constructor de la clase 'VistaInscripcion'
     */
    public VistaInscripcion()
    {
        setSize(getWidth(), getHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_altaActividad = new javax.swing.JButton();
        jButton_bajaActividad = new javax.swing.JButton();
        jLabel_titulo = new javax.swing.JLabel();
        jScrollPane_socios = new javax.swing.JScrollPane();
        jTable_inscripcionSocios = new javax.swing.JTable();

        jButton_altaActividad.setText("Dar de Alta");
        jButton_altaActividad.setActionCommand("AltaActividad");
        jButton_altaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_altaActividadActionPerformed(evt);
            }
        });

        jButton_bajaActividad.setText("Dar de Baja");
        jButton_bajaActividad.setActionCommand("BajaActividad");
        jButton_bajaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bajaActividadActionPerformed(evt);
            }
        });

        jLabel_titulo.setFont(new java.awt.Font("Noto Sans Lao", 1, 36)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(0, 0, 153));
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Gestión de Inscripciones");
        jLabel_titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_titulo.setMaximumSize(new java.awt.Dimension(438, 100));
        jLabel_titulo.setMinimumSize(new java.awt.Dimension(438, 100));
        jLabel_titulo.setPreferredSize(new java.awt.Dimension(438, 100));

        jTable_inscripcionSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_socios.setViewportView(jTable_inscripcionSocios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_socios)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_altaActividad)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_bajaActividad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_socios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_altaActividad)
                    .addComponent(jButton_bajaActividad))
                .addContainerGap(282, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton 'Dar de Alta' del Socio en la Actividad
     * @param evt 
     */
    private void jButton_altaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_altaActividadActionPerformed
        
    }//GEN-LAST:event_jButton_altaActividadActionPerformed

    /**
     * Boton 'Dar de Baja' del Socio en la Actividad
     * @param evt 
     */
    private void jButton_bajaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bajaActividadActionPerformed
        
    }//GEN-LAST:event_jButton_bajaActividadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_altaActividad;
    public javax.swing.JButton jButton_bajaActividad;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JScrollPane jScrollPane_socios;
    public javax.swing.JTable jTable_inscripcionSocios;
    // End of variables declaration//GEN-END:variables
};
